name = "portfolio-frontend"
compatibility_date = "2023-09-18"

[env.production]
name = "portfolio-frontend"

[env.preview]
name = "portfolio-frontend-preview"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Pages configuration
[[pages]]
name = "portfolio-frontend"
source = "build"
destination = "https://your-custom-domain.com"

# Environment variables (set these in Cloudflare Pages dashboard)
[vars]
REACT_APP_API_URL = "https://your-backend-domain.com"
REACT_APP_ENVIRONMENT = "production"
